@proto = http
@host = localhost
@port = 3000
@baseApi = /api/chat
@baseUrl = {{proto}}://{{host}}:{{port}}{{baseApi}}

GET {{baseUrl}}/page/2 HTTP/1.1

###

POST {{baseUrl}}/2
content-type: application/json

{
    "content": "用中文一句话简要解释一下量子纠缠",
    "stream": false
}
