@proto = http
@host = localhost
@port = 3000
@baseApi = /api/user
@baseUrl = {{proto}}://{{host}}:{{port}}{{baseApi}}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Imx1Y194eiIsImVtYWlsIjoibHVjX3h6QHFxLmNvbSIsImlhdCI6MTc4MzQxMzU3OSwiZXhwIjoxNzgzNjcyNzc5fQ.Ozzy9cSbkMcHGlfml9bC8eL9vbr6oy5DciomqcZ1LQY

GET {{baseUrl}}/list HTTP/1.1
Authorization: Bearer {{token}}
###

GET {{baseUrl}}/page?page=1&pageSize=10&keyword=user1&createdAt=2025-11-24T00:00:00,2025-11-24T23:59:59 HTTP/1.1
Authorization: Bearer {{token}}
###

GET {{baseUrl}}/1
Authorization: Bearer {{token}}
###

POST {{baseUrl}}/register
content-type: application/json

{
    "name": "luc_xz",
    "email": "luc_xz@qq.com",
    "password": "9712170320_xz"
}

###

POST {{baseUrl}}/login
content-type: application/json

{
    "email": "luc_xz@qq.com",
    "password": "9712170320_xz"
}


###

PUT {{baseUrl}}/46
content-type: application/json

{
    "name": "default_user",
    "email": "default_user@example.com",
    "password": "123456"
}

###

DELETE {{baseUrl}}/41
content-type: application/json
