@proto = http
@host = localhost
@port = 3000
@baseApi = /api/user
@baseUrl = {{proto}}://{{host}}:{{port}}{{baseApi}}

GET {{baseUrl}}/list HTTP/1.1

###

GET {{baseUrl}}/page?page=1&pageSize=10&keyword=user1&createdAt=2025-11-24T00:00:00,2025-11-24T23:59:59 HTTP/1.1

###

POST {{baseUrl}}/
content-type: application/json

{
    "name": "third_user",
    "email": "test2@gmail.com",
    "password": "123456"
}

###

PUT {{baseUrl}}/46
content-type: application/json

{
    "name": "default_user",
    "email": "default_user@example.com",
    "password": "123456"
}

###

DELETE {{baseUrl}}/41
content-type: application/json
