param(
  [string]$MySqlServer = (Get-Command mysqld -ErrorAction Stop).Source,
  [string]$RedisServer = (Get-Command redis-server -ErrorAction Stop).Source
)
$ErrorActionPreference = 'Stop'
# Normalize duplicate PATH/Path entries in some Windows launcher environments (process only).
$pathValue = [Environment]::GetEnvironmentVariable('PATH', 'Process')
[Environment]::SetEnvironmentVariable('PATH', $null, 'Process')
[Environment]::SetEnvironmentVariable('Path', $null, 'Process')
[Environment]::SetEnvironmentVariable('Path', $pathValue, 'Process')
$root = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../..'))
$runtime = Join-Path $root '.test-services.local'
$envFile = Join-Path $root 'server/.env.test.local'
$utf8 = New-Object Text.UTF8Encoding($false)

function Resolve-Binary([string]$binary) {
  $shim = [IO.Path]::ChangeExtension($binary, '.shim')
  if (Test-Path -LiteralPath $shim) {
    $content = Get-Content -LiteralPath $shim -Raw
    if ($content -match 'path\s*=\s*"([^"]+)"') { return $matches[1] }
  }
  return (Resolve-Path -LiteralPath $binary).Path
}
function Assert-FreePort([int]$port) {
  $client = New-Object Net.Sockets.TcpClient
  try {
    if ($client.ConnectAsync('127.0.0.1', $port).Wait(500) -and $client.Connected) {
      throw "Port $port is already in use. Do not reuse an unknown service."
    }
  } catch [AggregateException] {
    # Connection refused means the local port is available.
  } finally { $client.Dispose() }
}
function Wait-Service([int]$port, [Diagnostics.Process]$process) {
  for ($attempt = 0; $attempt -lt 60; $attempt++) {
    if ($process.HasExited) { throw "Test service exited. Inspect $runtime logs." }
    $client = New-Object Net.Sockets.TcpClient
    try {
      if ($client.ConnectAsync('127.0.0.1', $port).Wait(200) -and $client.Connected) { return }
    } catch [AggregateException] {} finally { $client.Dispose() }
    Start-Sleep -Seconds 1
  }
  throw "Timed out waiting for test service on $port."
}

$MySqlServer = Resolve-Binary $MySqlServer
$RedisServer = Resolve-Binary $RedisServer
Assert-FreePort 13306
Assert-FreePort 16379
New-Item -ItemType Directory -Path $runtime -Force | Out-Null
$configFile = Join-Path $runtime 'services.json'
if (-not (Test-Path -LiteralPath $configFile)) {
  if (Test-Path -LiteralPath $envFile) { throw 'Existing .env.test.local is not owned by this helper; refusing to overwrite it.' }
  $config = @{
    mysqlPassword = [Guid]::NewGuid().ToString('N')
    rootPassword = [Guid]::NewGuid().ToString('N')
    redisPassword = [Guid]::NewGuid().ToString('N')
  }
  [IO.File]::WriteAllText($configFile, ($config | ConvertTo-Json), $utf8)
}
$config = Get-Content -LiteralPath $configFile -Raw | ConvertFrom-Json
$mysqlData = Join-Path $runtime 'mysql-data'
$redisData = Join-Path $runtime 'redis-data'
New-Item -ItemType Directory -Path $redisData -Force | Out-Null
$baseDir = Split-Path (Split-Path $MySqlServer -Parent) -Parent
if (-not (Test-Path -LiteralPath (Join-Path $mysqlData 'mysql'))) {
  & $MySqlServer --no-defaults --initialize-insecure "--basedir=$baseDir" "--datadir=$mysqlData" --console
  if ($LASTEXITCODE -ne 0) { throw 'Isolated MySQL initialization failed.' }
}
$initFile = Join-Path $runtime 'mysql-init.sql'
$initSql = @"
ALTER USER 'root'@'localhost' IDENTIFIED BY '$($config.rootPassword)';
CREATE DATABASE IF NOT EXISTS aura_test;
CREATE USER IF NOT EXISTS 'aura_test'@'127.0.0.1' IDENTIFIED BY '$($config.mysqlPassword)';
CREATE USER IF NOT EXISTS 'aura_test'@'localhost' IDENTIFIED BY '$($config.mysqlPassword)';
GRANT ALL PRIVILEGES ON aura_test.* TO 'aura_test'@'127.0.0.1';
GRANT ALL PRIVILEGES ON aura_test.* TO 'aura_test'@'localhost';
"@
[IO.File]::WriteAllText($initFile, $initSql, $utf8)
$redisConf = Join-Path $runtime 'redis.conf'
[IO.File]::WriteAllText($redisConf, @"
bind 127.0.0.1
port 16379
protected-mode yes
requirepass $($config.redisPassword)
save ""
appendonly no
dir "./redis-data"
"@, $utf8)
$mysqlArgs = @('--no-defaults', "--basedir=`"$baseDir`"", "--datadir=`"$mysqlData`"", '--bind-address=127.0.0.1', '--port=13306', '--mysqlx=OFF', "--init-file=`"$initFile`"", '--console')
$mysql = $null
$redis = $null
try {
  $mysql = Start-Process -FilePath $MySqlServer -ArgumentList $mysqlArgs -WorkingDirectory $runtime -WindowStyle Hidden -PassThru -RedirectStandardOutput (Join-Path $runtime 'mysql.out.log') -RedirectStandardError (Join-Path $runtime 'mysql.err.log')
  Wait-Service 13306 $mysql
  $redis = Start-Process -FilePath $RedisServer -ArgumentList 'redis.conf' -WorkingDirectory $runtime -WindowStyle Hidden -PassThru -RedirectStandardOutput (Join-Path $runtime 'redis.out.log') -RedirectStandardError (Join-Path $runtime 'redis.err.log')
  Wait-Service 16379 $redis
  [IO.File]::WriteAllText($envFile, @"
# Generated by start-test-services.ps1. Dedicated local services; NEVER business credentials.
TEST_ALLOW_RESET=aura_test
TEST_DB_HOST=127.0.0.1
TEST_DB_PORT=13306
TEST_DB_USER=aura_test
TEST_DB_PASSWORD=$($config.mysqlPassword)
TEST_REDIS_HOST=127.0.0.1
TEST_REDIS_PORT=16379
TEST_REDIS_PASSWORD=$($config.redisPassword)
"@, $utf8)
  [IO.File]::WriteAllText((Join-Path $runtime 'pids.json'), (@{ mysql = $mysql.Id; redis = $redis.Id } | ConvertTo-Json), $utf8)
  Write-Output "Isolated test services ready: MySQL 127.0.0.1:13306 / aura_test; Redis 127.0.0.1:16379."
  Write-Output "PIDs: MySQL=$($mysql.Id), Redis=$($redis.Id). Credentials stay in ignored local files."
} catch {
  if ($redis -and -not $redis.HasExited) { $redis.Kill() }
  if ($mysql -and -not $mysql.HasExited) { $mysql.Kill() }
  throw
}
