// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/chat": {
    params: {};
  };
  "/note": {
    params: {};
  };
  "/note/edit/:id?": {
    params: {
      "id"?: string;
    };
  };
  "/setting": {
    params: {};
  };
  "/setting/model-config": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/chat" | "/note" | "/note/edit/:id?" | "/setting" | "/setting/model-config";
  };
  "./pages/index.tsx": {
    id: "pages/index";
    page: "/";
  };
  "./pages/login/index.tsx": {
    id: "pages/login/index";
    page: "/login";
  };
  "./pages/layout/index.tsx": {
    id: "pages/layout/index";
    page: "/chat" | "/note" | "/note/edit/:id?" | "/setting" | "/setting/model-config";
  };
  "./pages/chat/index.tsx": {
    id: "pages/chat/index";
    page: "/chat";
  };
  "./pages/note/index.tsx": {
    id: "pages/note/index";
    page: "/note";
  };
  "./pages/note/edit.tsx": {
    id: "pages/note/edit";
    page: "/note/edit/:id?";
  };
  "./pages/setting/index.tsx": {
    id: "pages/setting/index";
    page: "/setting";
  };
  "./pages/setting/model-config.tsx": {
    id: "pages/setting/model-config";
    page: "/setting/model-config";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "pages/index": typeof import("./src/./pages/index.tsx");
  "pages/login/index": typeof import("./src/./pages/login/index.tsx");
  "pages/layout/index": typeof import("./src/./pages/layout/index.tsx");
  "pages/chat/index": typeof import("./src/./pages/chat/index.tsx");
  "pages/note/index": typeof import("./src/./pages/note/index.tsx");
  "pages/note/edit": typeof import("./src/./pages/note/edit.tsx");
  "pages/setting/index": typeof import("./src/./pages/setting/index.tsx");
  "pages/setting/model-config": typeof import("./src/./pages/setting/model-config.tsx");
};